// e2e_test.cpp — runs the REAL whisperbox_core_impl.cpp (N instances, one
// process) over an in-process fake of delivery_module (test/fakesdk). Covers the
// PLAN Phase 6 scenarios that don't need a real Basecamp/Waku fleet:
//   A  create → feed on peers → respond → creator decrypts → confirm → respondent
//      sees "confirmed" → CSV matches
//   B  cold start: a late, empty node catches up quickly via SYNC_REQ
//   C  privacy: a third identity can't open a response; the public confirmation
//      can't be linked to a respondent address
//   +  restart persistence, whitelist(addresses), close, import-before-sync,
//      double-submit rejection.
// Build/run: test/run-e2e.sh
#include "whisperbox_core_impl.h"
#include "fake_bus.h"
#include <QElapsedTimer>
#include <execinfo.h>
#include <exception>
#include <cstdio>
#include <cstdlib>
#include <memory>
#include <unistd.h>
#include <fstream>
#include <set>
#include <filesystem>
#include <chrono>
#include <pwd.h>
#include <unistd.h>

using whisperbox::json;

// logos_events bodies are generated by the real builder; the fake no-ops them.
void WhisperboxCoreImpl::stateChanged(const std::string&) {}
void WhisperboxCoreImpl::statusChanged(const std::string&) {}

static int failures = 0, checks = 0;
#define CHECK(cond, label) do { checks++; if (cond) std::printf("  ok   %s\n", std::string(label).c_str()); \
    else { std::printf("  FAIL %s\n", std::string(label).c_str()); failures++; } } while (0)

static std::string g_base;

struct Peer {
    std::string name, dir;
    std::unique_ptr<FakeNode> node;
    std::unique_ptr<WhisperboxCoreImpl> core;
    void start() {
        setenv("WHISPERBOX_CORE_DATA", dir.c_str(), 1);
        node = std::make_unique<FakeNode>(); node->name = name;
        core = std::make_unique<WhisperboxCoreImpl>();
        core->modules().delivery_module.node = node.get();
        FakeBus::get().nodes.push_back(node.get());
        core->fakeStart();
    }
    void stop() {
        auto& v = FakeBus::get().nodes;
        v.erase(std::remove(v.begin(), v.end(), node.get()), v.end());
        core.reset(); node.reset();
    }
    ~Peer() { if (node) stop(); }   // always leave the bus before the node is freed
    json snap() { return json::parse(core->snapshot()); }
    json call(const std::string& r) { return json::parse(r); }
};

// WB_DUMP_FIXTURES=<dir>: write real snapshots for the QML render harness.
static void dumpFixture(Peer& p, const std::string& name) {
    const char* d = std::getenv("WB_DUMP_FIXTURES"); if (!d) return;
    std::ofstream o(std::string(d) + "/" + name + ".json", std::ios::trunc); o << p.snap().dump(2) << "\n";
}

static std::unique_ptr<Peer> mkPeer(const std::string& name) {
    auto p = std::make_unique<Peer>(); p->name = name; p->dir = g_base + "/" + name;
    p->start(); return p;
}
static void pump(int ms) {
    QElapsedTimer t; t.start();
    while (t.elapsed() < ms) { QCoreApplication::processEvents(QEventLoop::AllEvents, 20); usleep(2000); }
}
static bool waitUntil(std::function<bool()> pred, int ms) {
    QElapsedTimer t; t.start();
    while (t.elapsed() < ms) { if (pred()) return true; QCoreApplication::processEvents(QEventLoop::AllEvents, 20); usleep(2000); }
    return pred();
}
static bool hasForm(Peer& p, const std::string& fid) {
    json s = p.snap(); return s["state"]["forms"].contains(fid) && !s["state"]["forms"][fid]["questions"].empty();
}
static json formOf(Peer& p, const std::string& fid) { return p.snap()["state"]["forms"][fid]; }
static json responsesOf(Peer& p, const std::string& fid) {
    json s = p.snap();
    if (s["creatorView"].is_null() || !s["creatorView"]["responses"].contains(fid)) return json::array();
    return s["creatorView"]["responses"][fid];
}

int main(int argc, char** argv) {
    // Print a backtrace on an uncaught exception (diagnoses crashes that hide under gdb).
    std::set_terminate([] {
        void* fr[64]; int n = backtrace(fr, 64);
        try { if (auto ep = std::current_exception()) std::rethrow_exception(ep); }
        catch (const std::exception& ex) { std::fprintf(stderr, "UNCAUGHT: %s\n", ex.what()); } catch (...) {}
        backtrace_symbols_fd(fr, n, 2); std::abort();
    });
    QCoreApplication app(argc, argv);
    char tmpl[] = "/tmp/wb-e2e-XXXXXX";
    g_base = mkdtemp(tmpl);
    std::printf("data: %s\n", g_base.c_str());

    std::printf("boot:\n");
    auto A = mkPeer("A"), B = mkPeer("B"), C = mkPeer("C");
    CHECK(waitUntil([&] { return A->snap()["nodeReady"] == true && B->snap()["nodeReady"] == true; }, 3000), "nodes come up");
    dumpFixture(*A, "empty");       // fresh install, no forms yet
    std::string devA = A->snap()["deviceId"], devB = B->snap()["deviceId"];
    CHECK(devA != devB, "device ids are unique per install (" + devA + " vs " + devB + ")");
    std::string addrA = A->snap()["identity"]["address"], addrB = B->snap()["identity"]["address"], addrC = C->snap()["identity"]["address"];
    CHECK(addrA != addrB && addrB != addrC, "identities are distinct");

    // ── Scenario A ─────────────────────────────────────────────────────────────
    std::printf("scenario A (create → respond → decrypt → confirm → CSV):\n");
    json def = {{"title", "Lunch poll"}, {"description", "Friday team lunch"},
        {"questions", json::array({
            {{"id", "q1"}, {"type", "radioButtons"}, {"text", "Where?"}, {"required", true}, {"options", {"Sushi", "Pizza", "Tacos"}}},
            {{"id", "q2"}, {"type", "checkbox"}, {"text", "Dietary"}, {"required", false}, {"options", {"Vegan", "Gluten-free"}}},
            {{"id", "q3"}, {"type", "textarea"}, {"text", "Comments, \"quoted\""}, {"required", false}}})}};
    json cr = A->call(A->core->createForm(def.dump()));
    CHECK(cr.value("ok", false), "createForm ok");
    std::string fid = cr.value("formId", "");
    CHECK(waitUntil([&] { return hasForm(*B, fid) && hasForm(*C, fid); }, 3000), "form reaches B and C");
    json feedB = B->snap()["state"]["feed"];
    CHECK(std::find(feedB.begin(), feedB.end(), fid) != feedB.end(), "form is in B's public feed");

    // Wire format of every client: choice answers are option INDICES.
    json answers = json::array({{{"questionId", "q1"}, {"value", 1}},
                                {{"questionId", "q2"}, {"value", json::array({0})}},
                                {{"questionId", "q3"}, {"value", "no olives, please"}}});
    json sr = B->call(B->core->submitResponse(fid, answers.dump()));
    CHECK(sr.value("ok", false), "B submitResponse ok");
    json sr2 = B->call(B->core->submitResponse(fid, answers.dump()));
    CHECK(!sr2.value("ok", true), "B second submit rejected locally (one response per respondent)");
    CHECK(waitUntil([&] { return responsesOf(*A, fid).size() == 1; }, 3000), "A decrypts exactly one response");
    json r0 = responsesOf(*A, fid).empty() ? json::object() : responsesOf(*A, fid)[0];
    CHECK(r0.value("respondent", "") == addrB, "response attributed to B");
    CHECK(r0.contains("answers") && r0["answers"].dump() == answers.dump(), "answers round-trip exactly");
    CHECK(r0.value("confirmed", true) == false, "response starts unconfirmed");
    json bForm = formOf(*B, fid);
    CHECK(bForm.value("mySubmitted", false) == true, "B's snapshot marks the form submitted");
    CHECK(bForm.value("myConfirmed", true) == false, "B not yet confirmed");

    json cf = A->call(A->core->confirmResponse(fid, addrB));
    CHECK(cf.value("ok", false), "A confirmResponse ok");
    CHECK(waitUntil([&] { return !responsesOf(*A, fid).empty() && responsesOf(*A, fid)[0].value("confirmed", false); }, 2000), "A sees response confirmed");
    CHECK(waitUntil([&] { return formOf(*B, fid).value("myConfirmed", false); }, 3000), "B sees its response confirmed");

    json csv = A->call(A->core->exportCsv(fid));
    std::string csvs = csv.value("csv", "");
    CHECK(csv.value("ok", false) && csvs.find(",Pizza,") != std::string::npos && csvs.find(addrB) != std::string::npos, "CSV has B's row with radio index rendered as option text");
    CHECK(csvs.find("\"Comments, \"\"quoted\"\"\"") != std::string::npos, "CSV escapes header cells");
    CHECK(csvs.find(",Vegan,") != std::string::npos, "CSV renders checkbox indices as option text");
    json csvB = B->call(B->core->exportCsv(fid));
    CHECK(!csvB.value("ok", true), "non-creator cannot export CSV");

    // ── Scenario C (privacy) ───────────────────────────────────────────────────
    std::printf("scenario C (privacy):\n");
    json sC = C->snap();
    CHECK(sC["state"]["responses"].size() >= 1, "C holds the sealed blob (synced)");
    CHECK(sC["creatorView"].is_null(), "C has no creator view (decrypts nothing)");
    std::string blobs = sC["state"]["responses"].dump();
    CHECK(blobs.find(addrB.substr(2)) == std::string::npos && blobs.find("Pizza") == std::string::npos, "wire blob leaks neither respondent nor answers");
    {   // the public confirmation id must not be computable from (formId, respondent)
        std::string guess = fid + "|" + addrB;
        whisperbox::Bytes gb(guess.begin(), guess.end());
        std::string guessCid = whisperbox::toHex(whisperbox::sha256(gb).data(), 8);
        json confs = C->snap()["state"]["forms"][fid]["confirmations"];
        CHECK(confs.size() == 1, "C sees one public confirmation");
        CHECK(std::find(confs.begin(), confs.end(), guessCid) == confs.end(), "public confirmation is NOT linkable to the respondent's address");
    }

    // ── whitelist (addresses) ──────────────────────────────────────────────────
    std::printf("whitelist:\n");
    json wdef = {{"title", "Members only"}, {"questions", json::array({{{"id", "q1"}, {"type", "text"}, {"text", "Hi?"}, {"required", true}}})},
                 {"whitelist", {{"type", "addresses"}, {"value", addrB}}}};
    std::string wfid = A->call(A->core->createForm(wdef.dump())).value("formId", "");
    CHECK(waitUntil([&] { return hasForm(*B, wfid) && hasForm(*C, wfid); }, 3000), "whitelisted form syncs");
    json one = json::array({{{"questionId", "q1"}, {"value", "yo"}}});
    CHECK(B->call(B->core->submitResponse(wfid, one.dump())).value("ok", false), "whitelisted B submits");
    json cTry = C->call(C->core->submitResponse(wfid, one.dump()));
    CHECK(!cTry.value("ok", true), "non-whitelisted C is refused locally");
    pump(800);
    json wr = responsesOf(*A, wfid);
    CHECK(wr.size() == 1 && wr[0].value("respondent", "") == addrB, "creator accepts only the whitelisted respondent");

    // adversarial: C bypasses its own core and publishes a validly SIGNED, sealed
    // response to the members-only form straight onto the wire.
    {
        std::ifstream idf(C->dir + "/identity.json"); json idj = json::parse(idf);
        whisperbox::SignId cid = whisperbox::identityFromPriv(whisperbox::fromHex(idj["privHex"].get<std::string>()));
        whisperbox::OrderedJson m = whisperbox::OrderedJson::object();
        m["formId"] = wfid; m["respondent"] = cid.address; m["submittedAt"] = 1; m["answers"] = one;
        std::string msg = "whisperbox-inner-v1|" + m.dump();
        whisperbox::Bytes dg = whisperbox::sha256(whisperbox::Bytes(msg.begin(), msg.end()));
        whisperbox::OrderedJson resp = m;
        resp["signature"] = whisperbox::toHex(whisperbox::ecdsaSignLowS(cid.priv, dg)); resp["pub"] = cid.pubHex;
        std::string pt = resp.dump();
        std::string sealed = whisperbox::toHex(whisperbox::eciesSeal(whisperbox::fromHex(formOf(*A, wfid)["publicKey"].get<std::string>()), whisperbox::Bytes(pt.begin(), pt.end())));
        json ev = {{"v", 1}, {"id", whisperbox::responseSubmitId(sealed)}, {"type", "response.submit"},
                   {"hlc", {{"wall", 2}, {"ctr", 0}, {"dev", "evil"}}}, {"dev", "evil"}, {"payload", {{"encryptedPayload", sealed}}}};
        std::string b64 = whisperbox::b64encode(whisperbox::eventToJsonText(whisperbox::envEvent(ev)));
        FakeBus::get().relay(C->node.get(), whisperbox::TOPIC, b64);
        pump(500);
        json wr2 = responsesOf(*A, wfid);
        CHECK(wr2.size() == 1 && wr2[0].value("respondent", "") == addrB, "forged signed response from unlisted C is dropped by the creator");
        CHECK(A->snap()["creatorView"]["dropped"]["reasons"].value("not-whitelisted", 0) == 1, "creator counts it as not-whitelisted");
    }

    // legacy respondent (<= 0.1.x: no sealed confirmationId, array my_submissions)
    std::printf("legacy compat:\n");
    {
        std::string lfid = A->call(A->core->createForm(json({{"title", "Legacy"}, {"questions", json::array({{{"id", "q1"}, {"type", "text"}, {"text", "?"}}})}}).dump())).value("formId", "");
        CHECK(waitUntil([&] { return hasForm(*C, lfid); }, 3000), "legacy test form syncs");
        std::ifstream idf(C->dir + "/identity.json"); json idj = json::parse(idf);
        whisperbox::OrderedJson resp = whisperbox::OrderedJson::object();
        resp["formId"] = lfid; resp["respondent"] = addrC; resp["submittedAt"] = 5;
        resp["answers"] = json::array({{{"questionId", "q1"}, {"value", "old client"}}}); resp["signature"] = nullptr; resp["pub"] = nullptr;
        std::string pt = resp.dump();
        std::string sealed = whisperbox::toHex(whisperbox::eciesSeal(whisperbox::fromHex(formOf(*A, lfid)["publicKey"].get<std::string>()), whisperbox::Bytes(pt.begin(), pt.end())));
        json ev = {{"v", 1}, {"id", whisperbox::responseSubmitId(sealed)}, {"type", "response.submit"},
                   {"hlc", {{"wall", 3}, {"ctr", 0}, {"dev", "old"}}}, {"dev", "old"}, {"payload", {{"encryptedPayload", sealed}}}};
        FakeBus::get().relay(C->node.get(), whisperbox::TOPIC, whisperbox::b64encode(whisperbox::eventToJsonText(whisperbox::envEvent(ev))));
        C->stop();
        { std::ofstream o(C->dir + "/my_submissions.json", std::ios::trunc); o << json::array({lfid}).dump(); }   // 0.1.x format
        C->start();
        CHECK(waitUntil([&] { return responsesOf(*A, lfid).size() == 1; }, 3000), "creator decrypts the legacy response");
        CHECK(A->call(A->core->confirmResponse(lfid, addrC)).value("ok", false), "creator confirms the legacy response");
        CHECK(waitUntil([&] { return formOf(*C, lfid).value("myConfirmed", false); }, 3000), "legacy respondent recognises its (hash) receipt");
    }

    dumpFixture(*A, "creator");     // 2 forms (one members-only), confirmed + unconfirmed responses
    dumpFixture(*B, "respondent");  // answered + confirmed, members-only answered
    dumpFixture(*C, "outsider");    // can't answer the members-only form

    // ── close ──────────────────────────────────────────────────────────────────
    std::printf("close:\n");
    CHECK(!B->call(B->core->closeForm(fid)).value("ok", true), "non-creator cannot close");
    CHECK(A->call(A->core->closeForm(fid)).value("ok", false), "creator closes");
    CHECK(waitUntil([&] { return formOf(*C, fid).value("status", "") == "closed"; }, 3000), "close propagates");
    CHECK(!C->call(C->core->submitResponse(fid, answers.dump())).value("ok", true), "submit to closed form refused");
    CHECK(responsesOf(*A, fid).size() == 1, "closed form keeps its pre-close response");

    // ── Scenario B (cold start) ────────────────────────────────────────────────
    std::printf("scenario B (cold start):\n");
    auto D = mkPeer("D");
    QElapsedTimer t; t.start();
    bool caught = waitUntil([&] { return hasForm(*D, fid) && hasForm(*D, wfid); }, 15000);
    CHECK(caught, "late node D catches up on all forms");
    CHECK(t.elapsed() < 8000, "catch-up is driven by SYNC_REQ, not the 60s seed (" + std::to_string(t.elapsed()) + " ms)");
    CHECK(waitUntil([&] { return D->snap()["state"]["responses"].size() == A->snap()["state"]["responses"].size(); }, 5000), "D has the full response pool");
    {
        long rb = D->snap()["diagnostics"].value("rbsrRx", 0L);
        long legacy = A->snap()["diagnostics"].value("legacyReseeds", 0L) + B->snap()["diagnostics"].value("legacyReseeds", 0L)
                    + C->snap()["diagnostics"].value("legacyReseeds", 0L);
        CHECK(rb > 0, "D reconciled via RBSR (" + std::to_string(rb) + " control frames)");
        CHECK(legacy == 0, "no whole-log reseeds between 0.2 peers");
    }

    std::printf("legacy 0.1.x peer:\n");
    {
        // A node that only speaks the old protocol: sends an UNFLAGGED SYNC_REQ and expects
        // the whole log back as EVENT envelopes.
        FakeNode old; old.name = "legacy"; old.up = true; old.subscribed = true; old.senderId = "legacy";
        std::set<std::string> got;
        old.onMsg = [&](const std::string&, const std::string&, const LogosMap& p, int64_t) {
            std::string once = whisperbox::b64decode(p["_bytes"].get<std::string>());
            for (const std::string& t : {whisperbox::b64decode(once), once}) {
                json env = whisperbox::parseEnvelope(t);
                if (env.is_object() && env.value("type", "") == "EVENT") { got.insert(env["event"].value("id", "")); break; }
            }
        };
        FakeBus::get().nodes.push_back(&old);
        json req = {{"v", 1}, {"type", "SYNC_REQ"}, {"from", "legacy"}};
        FakeBus::get().relay(&old, whisperbox::TOPIC, whisperbox::b64encode(req.dump()));
        size_t want = 0; { json a = json::parse(std::ifstream(A->dir + "/events.json")); want = a.size(); }
        CHECK(waitUntil([&] { return got.size() >= want; }, 5000), "legacy peer receives the whole log (" + std::to_string(got.size()) + "/" + std::to_string(want) + ")");
        auto& v = FakeBus::get().nodes; v.erase(std::remove(v.begin(), v.end(), &old), v.end());
    }

    std::printf("partition heal:\n");
    {
        D->node->online = false;
        std::string pf = A->call(A->core->createForm(json({{"title", "While D was away"}, {"questions", json::array({{{"id", "q1"}, {"type", "text"}, {"text", "?"}}})}}).dump())).value("formId", "");
        pump(400);
        CHECK(!hasForm(*D, pf), "offline D missed the new form");
        D->node->online = true;
        D->core->resync();
        CHECK(waitUntil([&] { return hasForm(*D, pf); }, 4000), "D reconciles the missed form via RBSR after reconnect");
    }

    // ── import before sync (share link opened on a node that hasn't synced) ────
    std::printf("import-before-sync:\n");
    std::string uri = A->call(A->core->shareUri(fid)).value("uri", "");
    CHECK(uri == "whisperbox://form?id=" + fid + "&by=" + addrA, "shareUri is the short id form, pinned to the creator");
    std::string ifid = A->call(A->core->createForm(json({{"title", "Fresh"}, {"questions", json::array({{{"id", "q1"}, {"type", "text"}, {"text", "?"}}})}}).dump())).value("formId", "");
    auto E = mkPeer("E");
    E->node->online = false;   // offline: link opened before any sync
    json im = E->call(E->core->importForm("whisperbox://form?id=" + ifid));
    CHECK(im.value("ok", false), "importForm accepts the short link offline");
    json ew = E->snap()["watched"];
    CHECK(std::find(ew.begin(), ew.end(), ifid) != ew.end(), "imported form is watched");
    dumpFixture(*E, "pending");     // imported link, def not synced yet
    E->node->online = true;
    E->core->resync();
    CHECK(waitUntil([&] { return hasForm(*E, ifid) && formOf(*E, ifid).value("title", "") == "Fresh"; }, 8000), "canonical form def fills in after sync");
    CHECK(!formOf(*E, ifid).value("publicKey", "").empty(), "imported form has the creator key (answerable)");

    // ── id squatting: a back-dated, validly SIGNED copy of A's form id from C ──
    std::printf("id squatting:\n");
    {
        std::string sfid = A->call(A->core->createForm(json({{"title", "Salary survey"}, {"questions", json::array({{{"id", "q1"}, {"type", "text"}, {"text", "Salary?"}, {"required", true}}})}}).dump())).value("formId", "");
        CHECK(waitUntil([&] { return hasForm(*B, sfid) && hasForm(*C, sfid); }, 3000), "genuine form syncs");
        std::ifstream idf(C->dir + "/identity.json"); json idj = json::parse(idf);
        whisperbox::SignId xid = whisperbox::identityFromPriv(whisperbox::fromHex(idj["privHex"].get<std::string>()));
        json p = {{"id", sfid}, {"title", "Salary survey"}, {"description", ""}, {"creator", xid.address}, {"publicKey", xid.pubHex},
                  {"createdAt", 1}, {"expiresAt", nullptr}, {"questions", json::array({{{"id", "q1"}, {"type", "text"}, {"text", "Salary?"}, {"required", true}}})},
                  {"whitelist", {{"type", "none"}, {"value", ""}}}};
        json ev = {{"v", 1}, {"id", "form:" + sfid}, {"type", "form.publish"}, {"hlc", {{"wall", 1}, {"ctr", 0}, {"dev", "x"}}}, {"dev", "x"}, {"payload", p}};
        whisperbox::signEventJson(ev, xid);
        FakeBus::get().relay(C->node.get(), whisperbox::TOPIC, whisperbox::b64encode(whisperbox::eventToJsonText(whisperbox::envEvent(ev))));
        CHECK(waitUntil([&] { return formOf(*A, sfid).value("contested", false); }, 3000), "the squat reaches A and flags the id contested");
        CHECK(formOf(*A, sfid).value("creator", "") == addrA && formOf(*A, sfid).value("mine", false), "A still sees and owns its genuine form");
        std::string link = A->call(A->core->shareUri(sfid)).value("uri", "");
        auto G = mkPeer("G");
        CHECK(waitUntil([&] { return G->snap()["nodeReady"] == true; }, 3000), "G up");
        CHECK(G->call(G->core->importForm(link)).value("ok", false), "G opens the creator's pinned link");
        CHECK(waitUntil([&] { return hasForm(*G, sfid) && formOf(*G, sfid).value("contested", false); }, 8000), "G syncs both copies");
        json gf = formOf(*G, sfid);
        CHECK(gf.value("creator", "") == addrA && gf.value("canRespond", false), "pinned link shows the GENUINE form and allows answering");
        json one = json::array({{{"questionId", "q1"}, {"value", "plenty"}}});
        CHECK(G->call(G->core->submitResponse(sfid, one.dump())).value("ok", false), "G answers");
        CHECK(waitUntil([&] { return responsesOf(*A, sfid).size() == 1; }, 4000), "...and only the real creator A can read it");
        auto H = mkPeer("H");
        CHECK(waitUntil([&] { return H->snap()["nodeReady"] == true; }, 3000), "H up");
        H->call(H->core->importForm("whisperbox://form?id=" + sfid));   // an old, unpinned link
        CHECK(waitUntil([&] { return hasForm(*H, sfid) && formOf(*H, sfid).value("contested", false); }, 8000), "H syncs both copies");
        CHECK(!formOf(*H, sfid).value("canRespond", true), "unpinned link to a contested form: answering disabled");
        dumpFixture(*H, "contested");   // unpinned peer looking at a squatted form id
        json hr = H->call(H->core->submitResponse(sfid, one.dump()));
        CHECK(!hr.value("ok", true), "unpinned submit refused (" + hr.value("error", std::string()) + ")");
    }

    // ── restart persistence ────────────────────────────────────────────────────
    std::printf("restart:\n");
    size_t logBefore = A->snap()["state"]["responses"].size();
    A->stop(); A->start();
    CHECK(A->snap()["identity"]["address"] == addrA, "identity survives restart");
    CHECK(A->snap()["deviceId"] == devA, "device id survives restart");
    CHECK(A->snap()["state"]["responses"].size() == logBefore, "log survives restart");
    CHECK(responsesOf(*A, fid).size() == 1 && responsesOf(*A, fid)[0].value("confirmed", false), "decrypted + confirmed state survives restart");
    B->stop(); B->start();
    CHECK(formOf(*B, fid).value("myConfirmed", false), "respondent's confirmed state survives restart");

    // on-disk repair of a <= 0.1.x log: unsigned import placeholder + bad order
    std::printf("log repair:\n");
    {
        json events = json::parse(std::ifstream(A->dir + "/events.json"));
        json signedForm;
        for (auto& e : events) if (e.value("id", "") == "form:" + fid) signedForm = e;
        json placeholder = {{"v", 1}, {"id", "form:" + wfid}, {"type", "form.publish"}, {"hlc", {{"wall", 1}, {"ctr", 0}, {"dev", "x"}}},
                            {"dev", "x"}, {"payload", {{"id", wfid}, {"title", ""}, {"questions", json::array()}, {"publicKey", ""}}}};
        json bad = json::array(); bad.push_back(placeholder);
        for (auto it = events.rbegin(); it != events.rend(); ++it) if (it->value("id", "") != "form:" + wfid) bad.push_back(*it);   // reversed
        auto F = mkPeer("F"); F->node->online = false; F->stop();
        { std::ofstream o(F->dir + "/events.json", std::ios::trunc); o << bad.dump(); }
        F->start();
        json st = F->snap()["state"];
        CHECK(!st["forms"].contains(wfid), "unsigned placeholder dropped on load");
        CHECK(st["forms"].contains(fid) && !st["forms"][fid]["questions"].empty(), "signed forms kept");
        json ev2 = json::parse(std::ifstream(F->dir + "/events.json"));
        bool sorted = true;
        for (size_t k = 1; k < ev2.size(); ++k) if (whisperbox::totalOrder(ev2[k - 1], ev2[k]) > 0) sorted = false;
        CHECK(sorted, "repaired log is HLC-sorted on disk");
        F->node->online = true; F->core->resync();
        CHECK(waitUntil([&] { return hasForm(*F, wfid); }, 10000), "dropped form returns as the signed original via sync");
    }

    // ── per-form keys ────────────────────────────────────────────────────────────
    std::printf("per-form keys:\n");
    {
        auto relayEv = [&](const json& ev) { FakeBus::get().relay(C->node.get(), whisperbox::TOPIC, whisperbox::b64encode(whisperbox::eventToJsonText(whisperbox::envEvent(ev)))); };
        auto sealTo = [&](const std::string& pubHex, const whisperbox::OrderedJson& resp, int wall) {
            std::string pt = resp.dump();
            std::string sealed = whisperbox::toHex(whisperbox::eciesSeal(whisperbox::fromHex(pubHex), whisperbox::Bytes(pt.begin(), pt.end())));
            return json{{"v", 1}, {"id", whisperbox::responseSubmitId(sealed)}, {"type", "response.submit"},
                        {"hlc", {{"wall", wall}, {"ctr", 0}, {"dev", "k"}}}, {"dev", "k"}, {"payload", {{"encryptedPayload", sealed}}}};
        };
        const std::string pubA = A->snap()["identity"]["pubHex"];
        const std::string pk1 = formOf(*A, fid).value("publicKey", "");
        CHECK(!pk1.empty() && pk1 != pubA, "a new form seals to its OWN key, not the creator's identity key");
        std::string f2 = A->call(A->core->createForm(json({{"title", "Second"}, {"questions", json::array({{{"id", "q1"}, {"type", "text"}, {"text", "?"}}})}}).dump())).value("formId", "");
        CHECK(waitUntil([&] { return hasForm(*C, f2); }, 3000), "second form syncs");
        const std::string pk2 = formOf(*A, f2).value("publicKey", "");
        CHECK(!pk2.empty() && pk2 != pk1 && pk2 != pubA, "each form has a different key");
        std::ifstream idf(A->dir + "/identity.json"); json idj = json::parse(idf);
        whisperbox::SignId aid = whisperbox::identityFromPriv(whisperbox::fromHex(idj["privHex"].get<std::string>()));
        CHECK(whisperbox::deriveFormKey(aid, f2).pubHex == pk2, "the key is re-derivable from the identity (nothing extra to back up)");

        // A form key opens only its own form's answers; a blob sealed to form 1's key that
        // claims to answer form 2 is not accepted for either.
        whisperbox::OrderedJson cross = whisperbox::OrderedJson::object();
        cross["formId"] = f2; cross["respondent"] = addrC; cross["submittedAt"] = 7;
        cross["answers"] = json::array({{{"questionId", "q1"}, {"value", "cross"}}}); cross["signature"] = nullptr; cross["pub"] = nullptr;
        size_t n1 = responsesOf(*A, fid).size();
        relayEv(sealTo(pk1, cross, 7));
        pump(500);
        CHECK(responsesOf(*A, f2).empty() && responsesOf(*A, fid).size() == n1, "a blob sealed to another form's key is rejected");

        // Legacy form (0.2.0 and earlier): publicKey == the identity key - still opens.
        std::string lg = "form-legacykey";
        json p = {{"id", lg}, {"title", "Legacy key"}, {"description", ""}, {"creator", aid.address}, {"publicKey", aid.pubHex},
                  {"createdAt", 1}, {"expiresAt", nullptr}, {"questions", json::array({{{"id", "q1"}, {"type", "text"}, {"text", "?"}}})},
                  {"whitelist", {{"type", "none"}, {"value", ""}}}};
        json fe = {{"v", 1}, {"id", "form:" + lg}, {"type", "form.publish"}, {"hlc", {{"wall", 8}, {"ctr", 0}, {"dev", "old"}}}, {"dev", "old"}, {"payload", p}};
        whisperbox::signEventJson(fe, aid);
        relayEv(fe);
        CHECK(waitUntil([&] { return hasForm(*A, lg); }, 3000), "legacy-key form arrives");
        whisperbox::OrderedJson lr = whisperbox::OrderedJson::object();
        lr["formId"] = lg; lr["respondent"] = addrC; lr["submittedAt"] = 9;
        lr["answers"] = json::array({{{"questionId", "q1"}, {"value", "old key"}}}); lr["signature"] = nullptr; lr["pub"] = nullptr;
        relayEv(sealTo(aid.pubHex, lr, 9));
        CHECK(waitUntil([&] { return responsesOf(*A, lg).size() == 1; }, 3000), "answers to a legacy identity-key form still decrypt");
        A->stop(); A->start();
        CHECK(waitUntil([&] { return responsesOf(*A, f2).empty() && responsesOf(*A, lg).size() == 1 && responsesOf(*A, fid).size() == n1; }, 3000),
              "after a restart every form's answers still open (keys re-derived)");
    }

    // ── hide forms + my own answers (local, persisted) ───────────────────────────
    std::printf("hide + my answers:\n");
    {
        CHECK(B->call(B->core->hideForm(fid)).value("ok", false), "hideForm ok");
        CHECK(formOf(*B, fid).value("hidden", false) && B->snap()["hidden"].size() == 1, "form flagged hidden + listed in snapshot.hidden");
        dumpFixture(*B, "hidden");      // one answered form hidden (sidebar "Hidden" section)
        json mine = formOf(*B, fid)["myAnswers"];
        CHECK(mine.is_object() && mine["answers"].dump() == answers.dump(), "my submitted answers are kept (sealed blob opens only for the creator)");
        B->stop(); B->start();
        CHECK(formOf(*B, fid).value("hidden", false), "hidden survives a restart");
        CHECK(formOf(*B, fid).contains("myAnswers") && formOf(*B, fid)["myAnswers"]["answers"].dump() == answers.dump(), "my answers survive a restart");
        CHECK(formOf(*A, fid).value("hidden", true) == false, "hiding is local - other peers unaffected");
        CHECK(B->call(B->core->unhideForm(fid)).value("ok", false) && !formOf(*B, fid).value("hidden", true), "unhideForm brings it back");
        CHECK(!formOf(*A, fid).contains("myAnswers"), "the creator has no 'myAnswers' for a form it didn't answer");
    }

    // ── 0.3.2 lifecycle: yes/no, answer cap + auto-close, re-open, confirm all,
    //    automatic receipts, response count, drafts + scheduled publish, answer drafts ──
    std::printf("lifecycle 0.3.2:\n");
    {
        auto G = mkPeer("G");
        std::string addrG = G->snap()["identity"]["address"];
        json qs = json::array({{{"id", "q1"}, {"type", "boolean"}, {"text", "Coming?"}, {"required", true}}});
        json cr = A->call(A->core->createForm(json({{"title", "Capped"}, {"questions", qs}, {"maxResponses", 2}, {"showResponseCount", true}}).dump()));
        std::string cf = cr.value("formId", "");
        CHECK(waitUntil([&] { return hasForm(*B, cf) && hasForm(*C, cf) && hasForm(*G, cf); }, 3000), "capped form syncs");
        CHECK(formOf(*B, cf).value("maxResponses", 0) == 2 && formOf(*B, cf).value("showResponseCount", false), "cap + show-count travel with the form");
        CHECK(B->call(B->core->submitResponse(cf, json::array({{{"questionId", "q1"}, {"value", true}}}).dump())).value("ok", false), "B answers yes (boolean)");
        CHECK(C->call(C->core->submitResponse(cf, json::array({{{"questionId", "q1"}, {"value", false}}}).dump())).value("ok", false), "C answers no (false is a real answer)");
        CHECK(waitUntil([&] { return responsesOf(*A, cf).size() == 2; }, 3000), "creator decrypts both");
        CHECK(waitUntil([&] { return formOf(*G, cf).value("status", "") == "closed"; }, 9000), "form auto-closes at its answer cap and peers see it");
        CHECK(!G->call(G->core->submitResponse(cf, json::array({{{"questionId", "q1"}, {"value", true}}}).dump())).value("ok", true), "a third answer is refused once closed");
        std::string csv = A->call(A->core->exportCsv(cf)).value("csv", "");
        CHECK(csv.find(",Yes") != std::string::npos && csv.find(",No") != std::string::npos, "CSV renders yes/no");

        CHECK(A->call(A->core->confirmAll(cf)).value("events", 0) == 1, "confirm all = ONE receipt event for both");
        CHECK(waitUntil([&] { return formOf(*B, cf).value("myConfirmed", false) && formOf(*C, cf).value("myConfirmed", false); }, 3000), "both respondents see their receipt");
        CHECK(formOf(*G, cf)["confirmations"].size() == 2, "anyone can count responses from receipts (show-count)");
        CHECK(A->call(A->core->confirmAll(cf)).value("confirmed", -1) == 0, "confirm all again: nothing left to confirm");

        // Re-open an uncapped form: closed -> open again, new answers count.
        std::string rf = A->call(A->core->createForm(json({{"title", "Reopen me"}, {"questions", qs}}).dump())).value("formId", "");
        CHECK(waitUntil([&] { return hasForm(*G, rf); }, 3000), "second form syncs");
        CHECK(A->call(A->core->closeForm(rf)).value("ok", false) && A->call(A->core->closeForm(rf)).value("ok", false), "close (twice is fine)");
        CHECK(waitUntil([&] { return formOf(*G, rf).value("status", "") == "closed"; }, 3000), "peers see it closed");
        CHECK(A->call(A->core->reopenForm(rf)).value("ok", false), "reopenForm ok");
        CHECK(waitUntil([&] { return formOf(*G, rf).value("status", "") == "open"; }, 3000), "peers see it open again");
        CHECK(A->call(A->core->setAutoReceipts(rf, "1")).value("ok", false), "automatic receipts on");
        CHECK(G->call(G->core->submitResponse(rf, json::array({{{"questionId", "q1"}, {"value", true}}}).dump())).value("ok", false), "G answers after the re-open");
        CHECK(waitUntil([&] { return responsesOf(*A, rf).size() == 1; }, 3000), "the post-re-open answer counts");
        CHECK(waitUntil([&] { return formOf(*G, rf).value("myConfirmed", false); }, 9000), "automatic receipt reaches G without a click");
        CHECK(A->call(A->core->closeForm(rf)).value("ok", false), "close again after re-open (unique close ids)");
        CHECK(waitUntil([&] { return formOf(*G, rf).value("status", "") == "closed"; }, 3000), "second close propagates");

        // Drafts: local, survive restart; publish now / scheduled.
        json d1 = A->call(A->core->saveDraft(json({{"def", {{"title", "Draft now"}, {"questions", qs}}}}).dump()));
        long long soon = (long long)std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::system_clock::now().time_since_epoch()).count() + 1500;
        json d2 = A->call(A->core->saveDraft(json({{"def", {{"title", "Draft scheduled"}, {"questions", qs}}}, {"publishAt", soon}}).dump()));
        CHECK(d1.value("ok", false) && d2.value("ok", false) && A->snap()["drafts"].size() == 2, "two drafts saved");
        bool leaked = false;
        { json gs = G->snap(); for (auto& kv : gs["state"]["forms"].items()) if (kv.value().value("title", "").rfind("Draft", 0) == 0) leaked = true; }
        CHECK(!leaked, "drafts never leave the device");
        A->stop(); A->start();
        CHECK(A->snap()["drafts"].size() >= 1, "drafts survive a restart");
        // (keep the snapshot in a variable: iterating a temporary's sub-object is use-after-free)
        auto titled = [&](Peer& p, const std::string& t) { json ps = p.snap(); for (auto& kv : ps["state"]["forms"].items()) if (kv.value().value("title", "") == t) return true; return false; };
        CHECK(A->call(A->core->publishDraft(d1.value("draftId", ""))).value("ok", false), "publish a draft now");
        CHECK(waitUntil([&] { return titled(*G, "Draft now"); }, 3000), "published draft reaches peers");
        CHECK(waitUntil([&] { return titled(*G, "Draft scheduled"); }, 9000), "scheduled draft publishes itself when due");
        CHECK(waitUntil([&] { return A->snap()["drafts"].size() == 0; }, 3000), "published drafts are removed");

        // Answer drafts: kept across restart, cleared by submitting.
        std::string af = A->call(A->core->createForm(json({{"title", "Long form"}, {"questions", qs}}).dump())).value("formId", "");
        CHECK(waitUntil([&] { return hasForm(*G, af); }, 3000), "long form syncs");
        G->call(G->core->saveAnswerDraft(af, json::array({{{"questionId", "q1"}, {"value", true}}}).dump()));
        G->stop(); G->start();
        CHECK(formOf(*G, af).contains("answerDraft") && formOf(*G, af)["answerDraft"][0]["value"] == true, "a half-filled answer survives a restart");
        CHECK(G->call(G->core->submitResponse(af, json::array({{{"questionId", "q1"}, {"value", true}}}).dump())).value("ok", false) && !formOf(*G, af).contains("answerDraft"), "submitting clears the answer draft");
    }

    // ── data folder: never relative, adopt an identity kept elsewhere ────────────
    std::printf("data folder:\n");
    {
        // Simulate a module host with no usable WHISPERBOX_CORE_DATA and a HOME whose folder
        // holds an existing identity: a core with HOME pointing at it must adopt, not mint.
        auto K = mkPeer("H"); K->node->online = false;
        std::string addrH = K->snap()["identity"]["address"];
        std::string dirH = K->dir;
        K->stop();
        std::string fakeHome = g_base + "/home-h";
        std::filesystem::create_directories(fakeHome + "/.whisperbox-core");
        for (const char* fn : {"identity.json", "device_id.txt", "events.json"})
            std::filesystem::copy_file(dirH + "/" + fn, fakeHome + "/.whisperbox-core/" + fn, std::filesystem::copy_options::overwrite_existing);
        std::string savedData = std::getenv("WHISPERBOX_CORE_DATA") ? std::getenv("WHISPERBOX_CORE_DATA") : "";
        std::string savedHome = std::getenv("HOME") ? std::getenv("HOME") : "";
        std::string pwHome = g_base + "/pw-home";                 // the user-database home (empty)
        std::filesystem::create_directories(pwHome);
        auto startCore = [&](auto&& check) {
            FakeNode n; n.name = "h"; n.online = false;
            WhisperboxCoreImpl c; c.modules().delivery_module.node = &n;
            FakeBus::get().nodes.push_back(&n);
            c.fakeStart();
            check(json::parse(c.snapshot()));
            auto& v = FakeBus::get().nodes; v.erase(std::remove(v.begin(), v.end(), &n), v.end());
        };
        unsetenv("WHISPERBOX_CORE_DATA");
        setenv("WHISPERBOX_TEST_REAL_HOME", pwHome.c_str(), 1);
        setenv("HOME", fakeHome.c_str(), 1);                       // HOME differs and holds the identity
        startCore([&](const json& s) {
            CHECK(s["storage"]["dir"] == pwHome + "/.whisperbox-core", "the real home folder is used, never a relative path");
            CHECK(s["storage"]["ok"].get<bool>(), "data folder is writable");
            CHECK(s["identity"]["address"] == addrH, "an identity kept under HOME is adopted, not replaced");
        });
        unsetenv("HOME");                                          // module host without HOME
        startCore([&](const json& s) {
            CHECK(s["identity"]["address"] == addrH, "same identity after restart, even with HOME unset");
        });
        setenv("WHISPERBOX_CORE_DATA", "/proc/whisperbox-cannot-write", 1);
        startCore([&](const json& s) {
            CHECK(!s["storage"]["ok"].get<bool>() && !s["storage"]["note"].get<std::string>().empty(), "an unwritable data folder is reported in the snapshot");
        });
        unsetenv("WHISPERBOX_TEST_REAL_HOME");
        setenv("HOME", savedHome.c_str(), 1);
        if (!savedData.empty()) setenv("WHISPERBOX_CORE_DATA", savedData.c_str(), 1); else unsetenv("WHISPERBOX_CORE_DATA");
    }

    // Truncated files (module killed mid-write by an old version): never overwritten.
    std::printf("corrupt files:\n");
    {
        auto K = mkPeer("K"); K->node->online = false;
        std::string addrK = K->snap()["identity"]["address"];
        K->stop();
        { std::ofstream o(K->dir + "/events.json", std::ios::trunc); o << "[{\"v\":1,\"id\":\"form:x\",\"ty"; }      // truncated
        { std::ofstream o(K->dir + "/identity.json", std::ios::trunc); o << "{\"privHex\":\"ab"; }                     // truncated
        K->start();
        bool kept = false, keptId = false;
        for (const auto& de : std::filesystem::directory_iterator(K->dir)) {
            std::string n = de.path().filename().string();
            if (n.rfind("events.json.corrupt-", 0) == 0) kept = true;
            if (n.rfind("identity.json.corrupt-", 0) == 0) keptId = true;
        }
        CHECK(kept, "unreadable events.json is moved aside, not overwritten");
        CHECK(keptId, "unreadable identity.json is moved aside, not overwritten");
        CHECK(K->snap()["identity"]["address"] != addrK, "a fresh identity is created next to the quarantined one");
        CHECK(!std::filesystem::exists(K->dir + "/events.json.tmp"), "no temp file left behind");
    }

    std::printf("\n%d/%d checks passed\n", checks - failures, checks);
    if (!failures) std::system(("rm -rf '" + g_base + "'").c_str());
    std::printf(failures ? "E2E FAILED\n" : "E2E GREEN\n");
    return failures ? 1 : 0;
}
