// e2e_test.cpp — runs the REAL whisperbox_core_impl.cpp (N instances, one
// process) over an in-process fake of delivery_module (test/fakesdk). Covers the
// PLAN Phase 6 scenarios that don't need a real Basecamp/Waku fleet:
//   A  create → feed on peers → respond → creator decrypts → confirm → respondent
//      sees "confirmed" → CSV matches
//   B  cold start: a late, empty node catches up quickly via SYNC_REQ
//   C  privacy: a third identity can't open a response; the public confirmation
//      can't be linked to a respondent address
//   +  restart persistence, whitelist(addresses), close, import-before-sync,
//      double-submit rejection.
// Build/run: test/run-e2e.sh
#include "whisperbox_core_impl.h"
#include "fake_bus.h"
#include <QElapsedTimer>
#include <cstdio>
#include <cstdlib>
#include <memory>
#include <unistd.h>
#include <fstream>

using whisperbox::json;

// logos_events bodies are generated by the real builder; the fake no-ops them.
void WhisperboxCoreImpl::stateChanged(const std::string&) {}
void WhisperboxCoreImpl::statusChanged(const std::string&) {}

static int failures = 0, checks = 0;
#define CHECK(cond, label) do { checks++; if (cond) std::printf("  ok   %s\n", std::string(label).c_str()); \
    else { std::printf("  FAIL %s\n", std::string(label).c_str()); failures++; } } while (0)

static std::string g_base;

struct Peer {
    std::string name, dir;
    std::unique_ptr<FakeNode> node;
    std::unique_ptr<WhisperboxCoreImpl> core;
    void start() {
        setenv("WHISPERBOX_CORE_DATA", dir.c_str(), 1);
        node = std::make_unique<FakeNode>(); node->name = name;
        core = std::make_unique<WhisperboxCoreImpl>();
        core->modules().delivery_module.node = node.get();
        FakeBus::get().nodes.push_back(node.get());
        core->fakeStart();
    }
    void stop() {
        auto& v = FakeBus::get().nodes;
        v.erase(std::remove(v.begin(), v.end(), node.get()), v.end());
        core.reset(); node.reset();
    }
    json snap() { return json::parse(core->snapshot()); }
    json call(const std::string& r) { return json::parse(r); }
};

// WB_DUMP_FIXTURES=<dir>: write real snapshots for the QML render harness.
static void dumpFixture(Peer& p, const std::string& name) {
    const char* d = std::getenv("WB_DUMP_FIXTURES"); if (!d) return;
    std::ofstream o(std::string(d) + "/" + name + ".json", std::ios::trunc); o << p.snap().dump(2) << "\n";
}

static std::unique_ptr<Peer> mkPeer(const std::string& name) {
    auto p = std::make_unique<Peer>(); p->name = name; p->dir = g_base + "/" + name;
    p->start(); return p;
}
static void pump(int ms) {
    QElapsedTimer t; t.start();
    while (t.elapsed() < ms) { QCoreApplication::processEvents(QEventLoop::AllEvents, 20); usleep(2000); }
}
static bool waitUntil(std::function<bool()> pred, int ms) {
    QElapsedTimer t; t.start();
    while (t.elapsed() < ms) { if (pred()) return true; QCoreApplication::processEvents(QEventLoop::AllEvents, 20); usleep(2000); }
    return pred();
}
static bool hasForm(Peer& p, const std::string& fid) {
    json s = p.snap(); return s["state"]["forms"].contains(fid) && !s["state"]["forms"][fid]["questions"].empty();
}
static json formOf(Peer& p, const std::string& fid) { return p.snap()["state"]["forms"][fid]; }
static json responsesOf(Peer& p, const std::string& fid) {
    json s = p.snap();
    if (s["creatorView"].is_null() || !s["creatorView"]["responses"].contains(fid)) return json::array();
    return s["creatorView"]["responses"][fid];
}

int main(int argc, char** argv) {
    QCoreApplication app(argc, argv);
    char tmpl[] = "/tmp/wb-e2e-XXXXXX";
    g_base = mkdtemp(tmpl);
    std::printf("data: %s\n", g_base.c_str());

    std::printf("boot:\n");
    auto A = mkPeer("A"), B = mkPeer("B"), C = mkPeer("C");
    CHECK(waitUntil([&] { return A->snap()["nodeReady"] == true && B->snap()["nodeReady"] == true; }, 3000), "nodes come up");
    dumpFixture(*A, "empty");       // fresh install, no forms yet
    std::string devA = A->snap()["deviceId"], devB = B->snap()["deviceId"];
    CHECK(devA != devB, "device ids are unique per install (" + devA + " vs " + devB + ")");
    std::string addrA = A->snap()["identity"]["address"], addrB = B->snap()["identity"]["address"], addrC = C->snap()["identity"]["address"];
    CHECK(addrA != addrB && addrB != addrC, "identities are distinct");

    // ── Scenario A ─────────────────────────────────────────────────────────────
    std::printf("scenario A (create → respond → decrypt → confirm → CSV):\n");
    json def = {{"title", "Lunch poll"}, {"description", "Friday team lunch"},
        {"questions", json::array({
            {{"id", "q1"}, {"type", "radioButtons"}, {"text", "Where?"}, {"required", true}, {"options", {"Sushi", "Pizza", "Tacos"}}},
            {{"id", "q2"}, {"type", "checkbox"}, {"text", "Dietary"}, {"required", false}, {"options", {"Vegan", "Gluten-free"}}},
            {{"id", "q3"}, {"type", "textarea"}, {"text", "Comments, \"quoted\""}, {"required", false}}})}};
    json cr = A->call(A->core->createForm(def.dump()));
    CHECK(cr.value("ok", false), "createForm ok");
    std::string fid = cr.value("formId", "");
    CHECK(waitUntil([&] { return hasForm(*B, fid) && hasForm(*C, fid); }, 3000), "form reaches B and C");
    json feedB = B->snap()["state"]["feed"];
    CHECK(std::find(feedB.begin(), feedB.end(), fid) != feedB.end(), "form is in B's public feed");

    // Wire format of every client: choice answers are option INDICES.
    json answers = json::array({{{"questionId", "q1"}, {"value", 1}},
                                {{"questionId", "q2"}, {"value", json::array({0})}},
                                {{"questionId", "q3"}, {"value", "no olives, please"}}});
    json sr = B->call(B->core->submitResponse(fid, answers.dump()));
    CHECK(sr.value("ok", false), "B submitResponse ok");
    json sr2 = B->call(B->core->submitResponse(fid, answers.dump()));
    CHECK(!sr2.value("ok", true), "B second submit rejected locally (one response per respondent)");
    CHECK(waitUntil([&] { return responsesOf(*A, fid).size() == 1; }, 3000), "A decrypts exactly one response");
    json r0 = responsesOf(*A, fid).empty() ? json::object() : responsesOf(*A, fid)[0];
    CHECK(r0.value("respondent", "") == addrB, "response attributed to B");
    CHECK(r0.contains("answers") && r0["answers"].dump() == answers.dump(), "answers round-trip exactly");
    CHECK(r0.value("confirmed", true) == false, "response starts unconfirmed");
    json bForm = formOf(*B, fid);
    CHECK(bForm.value("mySubmitted", false) == true, "B's snapshot marks the form submitted");
    CHECK(bForm.value("myConfirmed", true) == false, "B not yet confirmed");

    json cf = A->call(A->core->confirmResponse(fid, addrB));
    CHECK(cf.value("ok", false), "A confirmResponse ok");
    CHECK(waitUntil([&] { return !responsesOf(*A, fid).empty() && responsesOf(*A, fid)[0].value("confirmed", false); }, 2000), "A sees response confirmed");
    CHECK(waitUntil([&] { return formOf(*B, fid).value("myConfirmed", false); }, 3000), "B sees its response confirmed");

    json csv = A->call(A->core->exportCsv(fid));
    std::string csvs = csv.value("csv", "");
    CHECK(csv.value("ok", false) && csvs.find(",Pizza,") != std::string::npos && csvs.find(addrB) != std::string::npos, "CSV has B's row with radio index rendered as option text");
    CHECK(csvs.find("\"Comments, \"\"quoted\"\"\"") != std::string::npos, "CSV escapes header cells");
    CHECK(csvs.find(",Vegan,") != std::string::npos, "CSV renders checkbox indices as option text");
    json csvB = B->call(B->core->exportCsv(fid));
    CHECK(!csvB.value("ok", true), "non-creator cannot export CSV");

    // ── Scenario C (privacy) ───────────────────────────────────────────────────
    std::printf("scenario C (privacy):\n");
    json sC = C->snap();
    CHECK(sC["state"]["responses"].size() >= 1, "C holds the sealed blob (synced)");
    CHECK(sC["creatorView"].is_null(), "C has no creator view (decrypts nothing)");
    std::string blobs = sC["state"]["responses"].dump();
    CHECK(blobs.find(addrB.substr(2)) == std::string::npos && blobs.find("Pizza") == std::string::npos, "wire blob leaks neither respondent nor answers");
    {   // the public confirmation id must not be computable from (formId, respondent)
        std::string guess = fid + "|" + addrB;
        whisperbox::Bytes gb(guess.begin(), guess.end());
        std::string guessCid = whisperbox::toHex(whisperbox::sha256(gb).data(), 8);
        json confs = C->snap()["state"]["forms"][fid]["confirmations"];
        CHECK(confs.size() == 1, "C sees one public confirmation");
        CHECK(std::find(confs.begin(), confs.end(), guessCid) == confs.end(), "public confirmation is NOT linkable to the respondent's address");
    }

    // ── whitelist (addresses) ──────────────────────────────────────────────────
    std::printf("whitelist:\n");
    json wdef = {{"title", "Members only"}, {"questions", json::array({{{"id", "q1"}, {"type", "text"}, {"text", "Hi?"}, {"required", true}}})},
                 {"whitelist", {{"type", "addresses"}, {"value", addrB}}}};
    std::string wfid = A->call(A->core->createForm(wdef.dump())).value("formId", "");
    CHECK(waitUntil([&] { return hasForm(*B, wfid) && hasForm(*C, wfid); }, 3000), "whitelisted form syncs");
    json one = json::array({{{"questionId", "q1"}, {"value", "yo"}}});
    CHECK(B->call(B->core->submitResponse(wfid, one.dump())).value("ok", false), "whitelisted B submits");
    json cTry = C->call(C->core->submitResponse(wfid, one.dump()));
    CHECK(!cTry.value("ok", true), "non-whitelisted C is refused locally");
    pump(800);
    json wr = responsesOf(*A, wfid);
    CHECK(wr.size() == 1 && wr[0].value("respondent", "") == addrB, "creator accepts only the whitelisted respondent");

    // adversarial: C bypasses its own core and publishes a validly SIGNED, sealed
    // response to the members-only form straight onto the wire.
    {
        std::ifstream idf(C->dir + "/identity.json"); json idj = json::parse(idf);
        whisperbox::SignId cid = whisperbox::identityFromPriv(whisperbox::fromHex(idj["privHex"].get<std::string>()));
        whisperbox::OrderedJson m = whisperbox::OrderedJson::object();
        m["formId"] = wfid; m["respondent"] = cid.address; m["submittedAt"] = 1; m["answers"] = one;
        std::string msg = "whisperbox-inner-v1|" + m.dump();
        whisperbox::Bytes dg = whisperbox::sha256(whisperbox::Bytes(msg.begin(), msg.end()));
        whisperbox::OrderedJson resp = m;
        resp["signature"] = whisperbox::toHex(whisperbox::ecdsaSignLowS(cid.priv, dg)); resp["pub"] = cid.pubHex;
        std::string pt = resp.dump();
        std::string sealed = whisperbox::toHex(whisperbox::eciesSeal(whisperbox::fromHex(formOf(*A, wfid)["publicKey"].get<std::string>()), whisperbox::Bytes(pt.begin(), pt.end())));
        json ev = {{"v", 1}, {"id", whisperbox::responseSubmitId(sealed)}, {"type", "response.submit"},
                   {"hlc", {{"wall", 2}, {"ctr", 0}, {"dev", "evil"}}}, {"dev", "evil"}, {"payload", {{"encryptedPayload", sealed}}}};
        std::string b64 = whisperbox::b64encode(whisperbox::eventToJsonText(whisperbox::envEvent(ev)));
        FakeBus::get().relay(C->node.get(), whisperbox::TOPIC, b64);
        pump(500);
        json wr2 = responsesOf(*A, wfid);
        CHECK(wr2.size() == 1 && wr2[0].value("respondent", "") == addrB, "forged signed response from unlisted C is dropped by the creator");
        CHECK(A->snap()["creatorView"]["dropped"]["reasons"].value("not-whitelisted", 0) == 1, "creator counts it as not-whitelisted");
    }

    // legacy respondent (<= 0.1.x: no sealed confirmationId, array my_submissions)
    std::printf("legacy compat:\n");
    {
        std::string lfid = A->call(A->core->createForm(json({{"title", "Legacy"}, {"questions", json::array({{{"id", "q1"}, {"type", "text"}, {"text", "?"}}})}}).dump())).value("formId", "");
        CHECK(waitUntil([&] { return hasForm(*C, lfid); }, 3000), "legacy test form syncs");
        std::ifstream idf(C->dir + "/identity.json"); json idj = json::parse(idf);
        whisperbox::OrderedJson resp = whisperbox::OrderedJson::object();
        resp["formId"] = lfid; resp["respondent"] = addrC; resp["submittedAt"] = 5;
        resp["answers"] = json::array({{{"questionId", "q1"}, {"value", "old client"}}}); resp["signature"] = nullptr; resp["pub"] = nullptr;
        std::string pt = resp.dump();
        std::string sealed = whisperbox::toHex(whisperbox::eciesSeal(whisperbox::fromHex(formOf(*A, lfid)["publicKey"].get<std::string>()), whisperbox::Bytes(pt.begin(), pt.end())));
        json ev = {{"v", 1}, {"id", whisperbox::responseSubmitId(sealed)}, {"type", "response.submit"},
                   {"hlc", {{"wall", 3}, {"ctr", 0}, {"dev", "old"}}}, {"dev", "old"}, {"payload", {{"encryptedPayload", sealed}}}};
        FakeBus::get().relay(C->node.get(), whisperbox::TOPIC, whisperbox::b64encode(whisperbox::eventToJsonText(whisperbox::envEvent(ev))));
        C->stop();
        { std::ofstream o(C->dir + "/my_submissions.json", std::ios::trunc); o << json::array({lfid}).dump(); }   // 0.1.x format
        C->start();
        CHECK(waitUntil([&] { return responsesOf(*A, lfid).size() == 1; }, 3000), "creator decrypts the legacy response");
        CHECK(A->call(A->core->confirmResponse(lfid, addrC)).value("ok", false), "creator confirms the legacy response");
        CHECK(waitUntil([&] { return formOf(*C, lfid).value("myConfirmed", false); }, 3000), "legacy respondent recognises its (hash) receipt");
    }

    dumpFixture(*A, "creator");     // 2 forms (one members-only), confirmed + unconfirmed responses
    dumpFixture(*B, "respondent");  // answered + confirmed, members-only answered
    dumpFixture(*C, "outsider");    // can't answer the members-only form

    // ── close ──────────────────────────────────────────────────────────────────
    std::printf("close:\n");
    CHECK(!B->call(B->core->closeForm(fid)).value("ok", true), "non-creator cannot close");
    CHECK(A->call(A->core->closeForm(fid)).value("ok", false), "creator closes");
    CHECK(waitUntil([&] { return formOf(*C, fid).value("status", "") == "closed"; }, 3000), "close propagates");
    CHECK(!C->call(C->core->submitResponse(fid, answers.dump())).value("ok", true), "submit to closed form refused");
    CHECK(responsesOf(*A, fid).size() == 1, "closed form keeps its pre-close response");

    // ── Scenario B (cold start) ────────────────────────────────────────────────
    std::printf("scenario B (cold start):\n");
    auto D = mkPeer("D");
    QElapsedTimer t; t.start();
    bool caught = waitUntil([&] { return hasForm(*D, fid) && hasForm(*D, wfid); }, 15000);
    CHECK(caught, "late node D catches up on all forms");
    CHECK(t.elapsed() < 8000, "catch-up is driven by SYNC_REQ, not the 60s seed (" + std::to_string(t.elapsed()) + " ms)");
    CHECK(waitUntil([&] { return D->snap()["state"]["responses"].size() == A->snap()["state"]["responses"].size(); }, 5000), "D has the full response pool");

    // ── import before sync (share link opened on a node that hasn't synced) ────
    std::printf("import-before-sync:\n");
    std::string uri = A->call(A->core->shareUri(fid)).value("uri", "");
    CHECK(uri == "whisperbox://form?id=" + fid, "shareUri is the short id form");
    std::string ifid = A->call(A->core->createForm(json({{"title", "Fresh"}, {"questions", json::array({{{"id", "q1"}, {"type", "text"}, {"text", "?"}}})}}).dump())).value("formId", "");
    auto E = mkPeer("E");
    E->node->online = false;   // offline: link opened before any sync
    json im = E->call(E->core->importForm("whisperbox://form?id=" + ifid));
    CHECK(im.value("ok", false), "importForm accepts the short link offline");
    json ew = E->snap()["watched"];
    CHECK(std::find(ew.begin(), ew.end(), ifid) != ew.end(), "imported form is watched");
    dumpFixture(*E, "pending");     // imported link, def not synced yet
    E->node->online = true;
    E->core->resync();
    CHECK(waitUntil([&] { return hasForm(*E, ifid) && formOf(*E, ifid).value("title", "") == "Fresh"; }, 8000), "canonical form def fills in after sync");
    CHECK(!formOf(*E, ifid).value("publicKey", "").empty(), "imported form has the creator key (answerable)");

    // ── restart persistence ────────────────────────────────────────────────────
    std::printf("restart:\n");
    size_t logBefore = A->snap()["state"]["responses"].size();
    A->stop(); A->start();
    CHECK(A->snap()["identity"]["address"] == addrA, "identity survives restart");
    CHECK(A->snap()["deviceId"] == devA, "device id survives restart");
    CHECK(A->snap()["state"]["responses"].size() == logBefore, "log survives restart");
    CHECK(responsesOf(*A, fid).size() == 1 && responsesOf(*A, fid)[0].value("confirmed", false), "decrypted + confirmed state survives restart");
    B->stop(); B->start();
    CHECK(formOf(*B, fid).value("myConfirmed", false), "respondent's confirmed state survives restart");

    // on-disk repair of a <= 0.1.x log: unsigned import placeholder + bad order
    std::printf("log repair:\n");
    {
        json events = json::parse(std::ifstream(A->dir + "/events.json"));
        json signedForm;
        for (auto& e : events) if (e.value("id", "") == "form:" + fid) signedForm = e;
        json placeholder = {{"v", 1}, {"id", "form:" + wfid}, {"type", "form.publish"}, {"hlc", {{"wall", 1}, {"ctr", 0}, {"dev", "x"}}},
                            {"dev", "x"}, {"payload", {{"id", wfid}, {"title", ""}, {"questions", json::array()}, {"publicKey", ""}}}};
        json bad = json::array(); bad.push_back(placeholder);
        for (auto it = events.rbegin(); it != events.rend(); ++it) if (it->value("id", "") != "form:" + wfid) bad.push_back(*it);   // reversed
        auto F = mkPeer("F"); F->node->online = false; F->stop();
        { std::ofstream o(F->dir + "/events.json", std::ios::trunc); o << bad.dump(); }
        F->start();
        json st = F->snap()["state"];
        CHECK(!st["forms"].contains(wfid), "unsigned placeholder dropped on load");
        CHECK(st["forms"].contains(fid) && !st["forms"][fid]["questions"].empty(), "signed forms kept");
        json ev2 = json::parse(std::ifstream(F->dir + "/events.json"));
        bool sorted = true;
        for (size_t k = 1; k < ev2.size(); ++k) if (whisperbox::totalOrder(ev2[k - 1], ev2[k]) > 0) sorted = false;
        CHECK(sorted, "repaired log is HLC-sorted on disk");
        F->node->online = true; F->core->resync();
        CHECK(waitUntil([&] { return hasForm(*F, wfid); }, 5000), "dropped form returns as the signed original via sync");
    }

    std::printf("\n%d/%d checks passed\n", checks - failures, checks);
    if (!failures) std::system(("rm -rf '" + g_base + "'").c_str());
    std::printf(failures ? "E2E FAILED\n" : "E2E GREEN\n");
    return failures ? 1 : 0;
}
