// parity_test.cpp — TS↔C++ byte-parity gate for whisperbox_core crypto.
// Reads the golden fixtures generated by packages/contract/test/gen-crypto-fixtures.mjs
// and checks, with the C++ implementation alone:
//   1. identityFromPriv reproduces pub + address (qaku convention)
//   2. verifyEvent accepts every TS-signed event (and rejects a tampered one)
//   3. eciesOpen decrypts every TS-sealed blob to the exact plaintext
//   4. eciesSeal (deterministic mode, same ephPriv) reproduces the TS blob BYTE-FOR-BYTE
// Usage: parity_test <repo-root>   (fixtures under <repo-root>/packages/contract/test/fixtures)
#include <cstdio>
#include <cstring>
#include <fstream>
#include <string>
#include "src/whisperbox_identity.hpp"

using namespace whisperbox;

static int failures = 0;
#define CHECK(cond, label) do { \
    if (cond) { std::printf("  ok   %s\n", label); } \
    else { std::printf("  FAIL %s\n", label); failures++; } \
} while (0)

static json loadJson(const std::string& path) {
    std::ifstream f(path);
    if (!f) { std::fprintf(stderr, "cannot open %s\n", path.c_str()); std::exit(2); }
    return json::parse(f);
}

int main(int argc, char** argv) {
    const std::string root = argc > 1 ? argv[1] : ".";
    const std::string fx = root + "/packages/contract/test/fixtures/";

    // ── 1. Identities ─────────────────────────────────────────────────────────
    std::printf("identities:\n");
    json idDoc = loadJson(fx + "crypto-identities.json");
    SignId byName[8];
    for (const auto& e : idDoc["identities"]) {
        const std::string name = e["name"];
        SignId id = identityFromPriv(fromHex(e["privHex"]));
        CHECK(id.valid, ("identity derives: " + name).c_str());
        CHECK(id.pubHex == e["pubHex"], ("pub matches TS: " + name).c_str());
        CHECK(id.address == e["address"], ("address matches TS: " + name).c_str());
        if (name == "alice") byName[0] = id;
        else if (name == "bob") byName[1] = id;
        else if (name == "carol") byName[2] = id;
    }

    // ── 2. Signed events ──────────────────────────────────────────────────────
    std::printf("signed events:\n");
    json evDoc = loadJson(fx + "crypto-signed-events.json");
    int nEv = 0;
    for (const auto& je : evDoc["events"]) {
        Event e;
        e.v = je.value("v", 1);
        e.id = je["id"]; e.type = je["type"];
        e.hlc.wall = je["hlc"]["wall"]; e.hlc.ctr = je["hlc"]["ctr"]; e.hlc.dev = je["hlc"]["dev"];
        e.dev = je.value("dev", "");
        e.payload = je["payload"];
        e.pub = je.value("pub", ""); e.sig = je.value("sig", "");
        char label[128];
        std::snprintf(label, sizeof label, "verifyEvent %s (%s)", e.id.c_str(), e.type.c_str());
        CHECK(verifyEvent(e), label);
        // Tamper: flip a payload field → must fail.
        Event t = e;
        if (t.payload.contains("title")) t.payload["title"] = "TAMPERED";
        else if (t.payload.contains("confirmationId")) t.payload["confirmationId"] = "conf-x";
        else t.payload["formId"] = "other-form";
        CHECK(!verifyEvent(t), (std::string("tamper rejects ") + e.id).c_str());
        nEv++;
    }
    CHECK(nEv == 3, "three signed events present");

    // ── 3+4. ECIES: open TS blobs AND re-seal byte-identically ────────────────
    std::printf("ecies:\n");
    json sealDoc = loadJson(fx + "crypto-sealed.json");
    int nSeal = 0;
    for (const auto& s : sealDoc["seals"]) {
        const std::string id = s["id"];
        const Bytes sealedTs = fromHex(s["sealedHex"]);
        const Bytes pt = strBytes(s["plaintext"].get<std::string>());

        // Open with the creator's (bob's) key.
        bool openedOk = false;
        try {
            const Bytes opened = eciesOpen(byName[1].priv, sealedTs);
            openedOk = (opened == pt);
        } catch (...) { openedOk = false; }
        CHECK(openedOk, ("open TS blob: " + id).c_str());

        // Re-seal deterministically with the same ephPriv → byte-identical.
        const Bytes ephPriv = fromHex(s["ephPrivHex"]);
        const Bytes resealed = eciesSeal(byName[1].pub, pt, &ephPriv, /*deterministic=*/true);
        CHECK(toHex(resealed) == s["sealedHex"], ("re-seal byte-identical: " + id).c_str());

        // Wrong creator (carol) must fail to open.
        bool wrongOk = false;
        try { eciesOpen(byName[2].priv, sealedTs); } catch (...) { wrongOk = true; }
        CHECK(wrongOk, ("wrong creator rejected: " + id).c_str());

        nSeal++;
    }
    CHECK(nSeal == 5, "five sealed blobs present");

    // ── 5. Random-ephemeral seal/open round-trip (the submitResponse path) ────
    std::printf("random eph round-trip:\n");
    {
        const Bytes pt = strBytes(R"({"formId":"form-x","respondent":"0xabc","answers":[]})");
        bool rtOk = false;
        try {
            const Bytes sealed = eciesSeal(byName[1].pub, pt); // random eph + nonce
            CHECK(sealed.size() == 1 + 33 + 12 + pt.size() + 16, "sealed length sane");
            const Bytes opened = eciesOpen(byName[1].priv, sealed);
            rtOk = (opened == pt);
        } catch (const std::exception& ex) {
            std::printf("  random-eph threw: %s\n", ex.what());
        }
        CHECK(rtOk, "random-eph seal→open round-trip");
    }

    std::printf(failures == 0 ? "\nPARITY GREEN\n" : "\nPARITY FAILED (%d)\n", failures);
    return failures == 0 ? 0 : 1;
}
